// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _37_Entity_Inheritance.Contexts;

#nullable disable

namespace _37_Entity_Inheritance.Migrations
{
    [DbContext(typeof(TPTAppDbContext))]
    [Migration("20251110111839_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.35")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("_37_Entity_Inheritance.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees", (string)null);
                });

            modelBuilder.Entity("_37_Entity_Inheritance.Models.Developer", b =>
                {
                    b.HasBaseType("_37_Entity_Inheritance.Models.Employee");

                    b.Property<string>("ProgLanguage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Developers", (string)null);
                });

            modelBuilder.Entity("_37_Entity_Inheritance.Models.Manager", b =>
                {
                    b.HasBaseType("_37_Entity_Inheritance.Models.Employee");

                    b.Property<int>("Bonus")
                        .HasColumnType("int");

                    b.ToTable("Managers", (string)null);
                });

            modelBuilder.Entity("_37_Entity_Inheritance.Models.Developer", b =>
                {
                    b.HasOne("_37_Entity_Inheritance.Models.Employee", null)
                        .WithOne()
                        .HasForeignKey("_37_Entity_Inheritance.Models.Developer", "Id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("_37_Entity_Inheritance.Models.Manager", b =>
                {
                    b.HasOne("_37_Entity_Inheritance.Models.Employee", null)
                        .WithOne()
                        .HasForeignKey("_37_Entity_Inheritance.Models.Manager", "Id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
